const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.solid,
		C3.Behaviors.Bullet,
		C3.Behaviors.jumpthru,
		C3.Behaviors.scrollto,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Plugins.Text,
		C3.Behaviors.Pin,
		C3.Behaviors.MoveTo,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.Scroll,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Platform.Exps.VectorX,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.PinByImagePoint
	];
};
self.C3_JsPropNameTable = [
	{Sólido: 0},
	{chão: 0},
	{Projétil: 0},
	{Sprite: 0},
	{PularAtravés: 0},
	{CentrarEm: 0},
	{Plataforma: 0},
	{RestritoAoLayout: 0},
	{personagem: 0},
	{porta: 0},
	{Sprite3: 0},
	{Texto2: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite2: 0},
	{Texto3: 0},
	{Texto: 0},
	{Fixar: 0},
	{personagem2: 0},
	{MoverPara: 0},
	{Texto4: 0},
	{Sprite6: 0},
	{moedas: 0},
	{armadilha: 0}
];

self.InstanceType = {
	chão: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	personagem: class extends self.ISpriteInstance {},
	porta: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Texto2: class extends self.ITextInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Texto3: class extends self.ITextInstance {},
	Texto: class extends self.ITextInstance {},
	personagem2: class extends self.ISpriteInstance {},
	Texto4: class extends self.ITextInstance {},
	Sprite6: class extends self.ISpriteInstance {}
}